# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import healer_pb2 as healer__pb2
import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in healer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterJob = channel.unary_unary(
                '/nemesis.healer.v1.HealerService/RegisterJob',
                request_serializer=healer__pb2.RegisterJobRequest.SerializeToString,
                response_deserializer=healer__pb2.RegisterJobResponse.FromString,
                _registered_method=True)
        self.ShrinkCommunicator = channel.unary_unary(
                '/nemesis.healer.v1.HealerService/ShrinkCommunicator',
                request_serializer=healer__pb2.ShrinkRequest.SerializeToString,
                response_deserializer=healer__pb2.ShrinkResult.FromString,
                _registered_method=True)
        self.ExpandCommunicator = channel.unary_unary(
                '/nemesis.healer.v1.HealerService/ExpandCommunicator',
                request_serializer=healer__pb2.ExpandRequest.SerializeToString,
                response_deserializer=healer__pb2.ExpandResult.FromString,
                _registered_method=True)
        self.ExecutePlaybook = channel.unary_unary(
                '/nemesis.healer.v1.HealerService/ExecutePlaybook',
                request_serializer=healer__pb2.PlaybookRequest.SerializeToString,
                response_deserializer=healer__pb2.PlaybookResult.FromString,
                _registered_method=True)
        self.ListPlaybooks = channel.unary_unary(
                '/nemesis.healer.v1.HealerService/ListPlaybooks',
                request_serializer=telemetry__pb2.Void.SerializeToString,
                response_deserializer=healer__pb2.PlaybookLibrary.FromString,
                _registered_method=True)


class HealerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShrinkCommunicator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCommunicator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePlaybook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaybooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterJob,
                    request_deserializer=healer__pb2.RegisterJobRequest.FromString,
                    response_serializer=healer__pb2.RegisterJobResponse.SerializeToString,
            ),
            'ShrinkCommunicator': grpc.unary_unary_rpc_method_handler(
                    servicer.ShrinkCommunicator,
                    request_deserializer=healer__pb2.ShrinkRequest.FromString,
                    response_serializer=healer__pb2.ShrinkResult.SerializeToString,
            ),
            'ExpandCommunicator': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCommunicator,
                    request_deserializer=healer__pb2.ExpandRequest.FromString,
                    response_serializer=healer__pb2.ExpandResult.SerializeToString,
            ),
            'ExecutePlaybook': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlaybook,
                    request_deserializer=healer__pb2.PlaybookRequest.FromString,
                    response_serializer=healer__pb2.PlaybookResult.SerializeToString,
            ),
            'ListPlaybooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaybooks,
                    request_deserializer=telemetry__pb2.Void.FromString,
                    response_serializer=healer__pb2.PlaybookLibrary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nemesis.healer.v1.HealerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nemesis.healer.v1.HealerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.healer.v1.HealerService/RegisterJob',
            healer__pb2.RegisterJobRequest.SerializeToString,
            healer__pb2.RegisterJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShrinkCommunicator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.healer.v1.HealerService/ShrinkCommunicator',
            healer__pb2.ShrinkRequest.SerializeToString,
            healer__pb2.ShrinkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandCommunicator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.healer.v1.HealerService/ExpandCommunicator',
            healer__pb2.ExpandRequest.SerializeToString,
            healer__pb2.ExpandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePlaybook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.healer.v1.HealerService/ExecutePlaybook',
            healer__pb2.PlaybookRequest.SerializeToString,
            healer__pb2.PlaybookResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaybooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.healer.v1.HealerService/ListPlaybooks',
            telemetry__pb2.Void.SerializeToString,
            healer__pb2.PlaybookLibrary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
