# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestMetrics = channel.stream_stream(
                '/nemesis.telemetry.v1.TelemetryService/IngestMetrics',
                request_serializer=telemetry__pb2.MetricSample.SerializeToString,
                response_deserializer=telemetry__pb2.Void.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/nemesis.telemetry.v1.TelemetryService/SubscribeEvents',
                request_serializer=telemetry__pb2.EventFilter.SerializeToString,
                response_deserializer=telemetry__pb2.HardwareEvent.FromString,
                _registered_method=True)
        self.GetClusterState = channel.unary_unary(
                '/nemesis.telemetry.v1.TelemetryService/GetClusterState',
                request_serializer=telemetry__pb2.Void.SerializeToString,
                response_deserializer=telemetry__pb2.ClusterSnapshot.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/nemesis.telemetry.v1.TelemetryService/PublishEvent',
                request_serializer=telemetry__pb2.HardwareEvent.SerializeToString,
                response_deserializer=telemetry__pb2.Void.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestMetrics(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.IngestMetrics,
                    request_deserializer=telemetry__pb2.MetricSample.FromString,
                    response_serializer=telemetry__pb2.Void.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=telemetry__pb2.EventFilter.FromString,
                    response_serializer=telemetry__pb2.HardwareEvent.SerializeToString,
            ),
            'GetClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterState,
                    request_deserializer=telemetry__pb2.Void.FromString,
                    response_serializer=telemetry__pb2.ClusterSnapshot.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=telemetry__pb2.HardwareEvent.FromString,
                    response_serializer=telemetry__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nemesis.telemetry.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nemesis.telemetry.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nemesis.telemetry.v1.TelemetryService/IngestMetrics',
            telemetry__pb2.MetricSample.SerializeToString,
            telemetry__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nemesis.telemetry.v1.TelemetryService/SubscribeEvents',
            telemetry__pb2.EventFilter.SerializeToString,
            telemetry__pb2.HardwareEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.telemetry.v1.TelemetryService/GetClusterState',
            telemetry__pb2.Void.SerializeToString,
            telemetry__pb2.ClusterSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.telemetry.v1.TelemetryService/PublishEvent',
            telemetry__pb2.HardwareEvent.SerializeToString,
            telemetry__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
