# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: topology.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'topology.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_pb2 as telemetry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etopology.proto\x12\x13nemesis.topology.v1\x1a\x0ftelemetry.proto\"B\n\x07JobSpec\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0ctopology_dsl\x18\x02 \x01(\t\x12\x11\n\tgpu_count\x18\x03 \x01(\r\"1\n\x10ValidationResult\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\"\x85\x01\n\x0fPlacementResult\x12\x0e\n\x06placed\x18\x01 \x01(\x08\x12\x0f\n\x07gpu_ids\x18\x02 \x03(\t\x12\x18\n\x10rejection_reason\x18\x03 \x01(\t\x12\x37\n\x08subgraph\x18\x04 \x01(\x0b\x32%.nemesis.telemetry.v1.ClusterTopology\" \n\x0eReleaseRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t2\xd1\x02\n\x10SchedulerService\x12O\n\x08Validate\x12\x1c.nemesis.topology.v1.JobSpec\x1a%.nemesis.topology.v1.ValidationResult\x12N\n\x08Schedule\x12\x1c.nemesis.topology.v1.JobSpec\x1a$.nemesis.topology.v1.PlacementResult\x12J\n\x07Release\x12#.nemesis.topology.v1.ReleaseRequest\x1a\x1a.nemesis.telemetry.v1.Void\x12P\n\x0bGetTopology\x12\x1a.nemesis.telemetry.v1.Void\x1a%.nemesis.telemetry.v1.ClusterTopologyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBSPEC']._serialized_start=56
  _globals['_JOBSPEC']._serialized_end=122
  _globals['_VALIDATIONRESULT']._serialized_start=124
  _globals['_VALIDATIONRESULT']._serialized_end=173
  _globals['_PLACEMENTRESULT']._serialized_start=176
  _globals['_PLACEMENTRESULT']._serialized_end=309
  _globals['_RELEASEREQUEST']._serialized_start=311
  _globals['_RELEASEREQUEST']._serialized_end=343
  _globals['_SCHEDULERSERVICE']._serialized_start=346
  _globals['_SCHEDULERSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
