# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2
import topology_pb2 as topology__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in topology_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/nemesis.topology.v1.SchedulerService/Validate',
                request_serializer=topology__pb2.JobSpec.SerializeToString,
                response_deserializer=topology__pb2.ValidationResult.FromString,
                _registered_method=True)
        self.Schedule = channel.unary_unary(
                '/nemesis.topology.v1.SchedulerService/Schedule',
                request_serializer=topology__pb2.JobSpec.SerializeToString,
                response_deserializer=topology__pb2.PlacementResult.FromString,
                _registered_method=True)
        self.Release = channel.unary_unary(
                '/nemesis.topology.v1.SchedulerService/Release',
                request_serializer=topology__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=telemetry__pb2.Void.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/nemesis.topology.v1.SchedulerService/GetTopology',
                request_serializer=telemetry__pb2.Void.SerializeToString,
                response_deserializer=telemetry__pb2.ClusterTopology.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=topology__pb2.JobSpec.FromString,
                    response_serializer=topology__pb2.ValidationResult.SerializeToString,
            ),
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=topology__pb2.JobSpec.FromString,
                    response_serializer=topology__pb2.PlacementResult.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=topology__pb2.ReleaseRequest.FromString,
                    response_serializer=telemetry__pb2.Void.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=telemetry__pb2.Void.FromString,
                    response_serializer=telemetry__pb2.ClusterTopology.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nemesis.topology.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nemesis.topology.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.topology.v1.SchedulerService/Validate',
            topology__pb2.JobSpec.SerializeToString,
            topology__pb2.ValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.topology.v1.SchedulerService/Schedule',
            topology__pb2.JobSpec.SerializeToString,
            topology__pb2.PlacementResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.topology.v1.SchedulerService/Release',
            topology__pb2.ReleaseRequest.SerializeToString,
            telemetry__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemesis.topology.v1.SchedulerService/GetTopology',
            telemetry__pb2.Void.SerializeToString,
            telemetry__pb2.ClusterTopology.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
